#################################################
# Environment
#################################################

ENV=DEV

BASE_URL=restful-booker.herokuapp.com

PROTOCOL=https

#################################################
# Performance
#################################################

THREADS=5

RAMPUP=5

LOOPS=1

DURATION=60

#################################################
# Reports
#################################################

REPORT_FOLDER=DEV