#################################################
# Tool Configuration
#################################################

JMETER_HOME=C:\Loadmagic\apache-jmeter-5.6.3\apache-jmeter-5.6.3

JAVA_HOME=C:\Program Files\Eclipse Adoptium\jdk-11.0.29.7-hotspot

PROJECT_HOME=E:\performance-onetouch-framework